# Generated by Django 5.0.4 on 2024-04-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTCUSD_info_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField()),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('index_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mark_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
